// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package dbgen

import (
	"context"
)

const dBHealthCheck = `-- name: DBHealthCheck :one
SELECT 1::int AS ok
`

func (q *Queries) DBHealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, dBHealthCheck)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
