// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package identitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearDefaultAddresses = `-- name: ClearDefaultAddresses :exec
UPDATE identity_addresses SET is_default = false WHERE user_id = $1 AND is_default
`

func (q *Queries) ClearDefaultAddresses(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultAddresses, userID)
	return err
}

const countAddresses = `-- name: CountAddresses :one
SELECT count(*) FROM identity_addresses WHERE user_id = $1
`

func (q *Queries) CountAddresses(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAddresses, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO identity_users (id, email, password_hash, name, role, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Role         string
	CreatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const deleteAddress = `-- name: DeleteAddress :execrows
DELETE FROM identity_addresses WHERE id = $1 AND user_id = $2
`

type DeleteAddressParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAddress, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM identity_refresh_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, tokenHash)
	return err
}

const deleteUserRefreshTokens = `-- name: DeleteUserRefreshTokens :exec
DELETE FROM identity_refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRefreshTokens, userID)
	return err
}

const getActivePasswordReset = `-- name: GetActivePasswordReset :one
SELECT id, user_id, token_hash, expires_at
FROM identity_password_resets
WHERE token_hash = $1 AND used_at IS NULL
`

type GetActivePasswordResetRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) GetActivePasswordReset(ctx context.Context, tokenHash string) (GetActivePasswordResetRow, error) {
	row := q.db.QueryRow(ctx, getActivePasswordReset, tokenHash)
	var i GetActivePasswordResetRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const getAddress = `-- name: GetAddress :one
SELECT id, user_id, recipient, line1, line2, city, region, postal_code, country, phone, is_default, created_at
FROM identity_addresses
WHERE id = $1 AND user_id = $2
`

type GetAddressParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAddress(ctx context.Context, arg GetAddressParams) (IdentityAddress, error) {
	row := q.db.QueryRow(ctx, getAddress, arg.ID, arg.UserID)
	var i IdentityAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Recipient,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.Region,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at
FROM identity_refresh_tokens WHERE token_hash = $1
`

type GetRefreshTokenRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, created_at
FROM identity_users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, created_at
FROM identity_users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertAddress = `-- name: InsertAddress :exec
INSERT INTO identity_addresses
    (id, user_id, recipient, line1, line2, city, region, postal_code, country, phone, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertAddressParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Recipient  string
	Line1      string
	Line2      string
	City       string
	Region     string
	PostalCode string
	Country    string
	Phone      string
	IsDefault  bool
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) error {
	_, err := q.db.Exec(ctx, insertAddress,
		arg.ID,
		arg.UserID,
		arg.Recipient,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.Region,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.IsDefault,
	)
	return err
}

const insertPasswordReset = `-- name: InsertPasswordReset :exec
INSERT INTO identity_password_resets (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertPasswordResetParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertPasswordReset(ctx context.Context, arg InsertPasswordResetParams) error {
	_, err := q.db.Exec(ctx, insertPasswordReset,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO identity_refresh_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, user_id, recipient, line1, line2, city, region, postal_code, country, phone, is_default, created_at
FROM identity_addresses
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListAddresses(ctx context.Context, userID uuid.UUID) ([]IdentityAddress, error) {
	rows, err := q.db.Query(ctx, listAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityAddress{}
	for rows.Next() {
		var i IdentityAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Recipient,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.Region,
			&i.PostalCode,
			&i.Country,
			&i.Phone,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE identity_password_resets SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, id)
	return err
}

const newestAddressID = `-- name: NewestAddressID :one
SELECT id FROM identity_addresses WHERE user_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) NewestAddressID(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, newestAddressID, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setAddressDefault = `-- name: SetAddressDefault :exec
UPDATE identity_addresses SET is_default = true WHERE id = $1 AND user_id = $2
`

type SetAddressDefaultParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SetAddressDefault(ctx context.Context, arg SetAddressDefaultParams) error {
	_, err := q.db.Exec(ctx, setAddressDefault, arg.ID, arg.UserID)
	return err
}

const updateAddress = `-- name: UpdateAddress :exec
UPDATE identity_addresses
SET recipient = $3, line1 = $4, line2 = $5, city = $6, region = $7,
    postal_code = $8, country = $9, phone = $10, is_default = $11
WHERE id = $1 AND user_id = $2
`

type UpdateAddressParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Recipient  string
	Line1      string
	Line2      string
	City       string
	Region     string
	PostalCode string
	Country    string
	Phone      string
	IsDefault  bool
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) error {
	_, err := q.db.Exec(ctx, updateAddress,
		arg.ID,
		arg.UserID,
		arg.Recipient,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.Region,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.IsDefault,
	)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE identity_users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE identity_users SET name = $2 WHERE id = $1
RETURNING id, email, password_hash, name, role, created_at
`

type UpdateUserNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE identity_users SET role = $2 WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
