// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityPasswordReset struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
	CreatedAt time.Time
}

type IdentityRefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type IdentityUser struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Role         string
	CreatedAt    time.Time
}

type PlatformOutbox struct {
	ID           uuid.UUID
	EventType    string
	Payload      []byte
	OccurredAt   time.Time
	DispatchedAt pgtype.Timestamptz
	CreatedAt    time.Time
}

type PlatformProcessedEvent struct {
	Consumer    string
	EventID     uuid.UUID
	ProcessedAt time.Time
}
