// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	GetActivePasswordReset(ctx context.Context, tokenHash string) (GetActivePasswordResetRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (GetRefreshTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (IdentityUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error)
	InsertPasswordReset(ctx context.Context, arg InsertPasswordResetParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) error
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
}

var _ Querier = (*Queries)(nil)
