// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sellerdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetActiveApplicationByUser(ctx context.Context, userID uuid.UUID) (GetActiveApplicationByUserRow, error)
	GetApplicationByID(ctx context.Context, id uuid.UUID) (GetApplicationByIDRow, error)
	GetLatestApplicationByUser(ctx context.Context, userID uuid.UUID) (GetLatestApplicationByUserRow, error)
	GetStoreBySeller(ctx context.Context, sellerID uuid.UUID) (GetStoreBySellerRow, error)
	InsertApplication(ctx context.Context, arg InsertApplicationParams) error
	InsertStore(ctx context.Context, arg InsertStoreParams) error
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) error
	UpdateStore(ctx context.Context, arg UpdateStoreParams) error
}

var _ Querier = (*Queries)(nil)
