// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seller.sql

package sellerdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getActiveApplicationByUser = `-- name: GetActiveApplicationByUser :one
SELECT id, user_id, status, store_name, description, contact, reject_reason, created_at
FROM seller_applications
WHERE user_id = $1 AND status IN ('pending', 'approved', 'suspended')
`

type GetActiveApplicationByUserRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Status       string
	StoreName    string
	Description  string
	Contact      string
	RejectReason string
	CreatedAt    time.Time
}

func (q *Queries) GetActiveApplicationByUser(ctx context.Context, userID uuid.UUID) (GetActiveApplicationByUserRow, error) {
	row := q.db.QueryRow(ctx, getActiveApplicationByUser, userID)
	var i GetActiveApplicationByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.StoreName,
		&i.Description,
		&i.Contact,
		&i.RejectReason,
		&i.CreatedAt,
	)
	return i, err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, user_id, status, store_name, description, contact, reject_reason, created_at
FROM seller_applications WHERE id = $1
`

type GetApplicationByIDRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Status       string
	StoreName    string
	Description  string
	Contact      string
	RejectReason string
	CreatedAt    time.Time
}

func (q *Queries) GetApplicationByID(ctx context.Context, id uuid.UUID) (GetApplicationByIDRow, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i GetApplicationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.StoreName,
		&i.Description,
		&i.Contact,
		&i.RejectReason,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestApplicationByUser = `-- name: GetLatestApplicationByUser :one
SELECT id, user_id, status, store_name, description, contact, reject_reason, created_at
FROM seller_applications WHERE user_id = $1 ORDER BY created_at DESC LIMIT 1
`

type GetLatestApplicationByUserRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Status       string
	StoreName    string
	Description  string
	Contact      string
	RejectReason string
	CreatedAt    time.Time
}

func (q *Queries) GetLatestApplicationByUser(ctx context.Context, userID uuid.UUID) (GetLatestApplicationByUserRow, error) {
	row := q.db.QueryRow(ctx, getLatestApplicationByUser, userID)
	var i GetLatestApplicationByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.StoreName,
		&i.Description,
		&i.Contact,
		&i.RejectReason,
		&i.CreatedAt,
	)
	return i, err
}

const getStoreBySeller = `-- name: GetStoreBySeller :one
SELECT id, seller_id, name, logo_url, description, contact
FROM seller_stores WHERE seller_id = $1
`

type GetStoreBySellerRow struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	LogoUrl     string
	Description string
	Contact     string
}

func (q *Queries) GetStoreBySeller(ctx context.Context, sellerID uuid.UUID) (GetStoreBySellerRow, error) {
	row := q.db.QueryRow(ctx, getStoreBySeller, sellerID)
	var i GetStoreBySellerRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.LogoUrl,
		&i.Description,
		&i.Contact,
	)
	return i, err
}

const insertApplication = `-- name: InsertApplication :exec
INSERT INTO seller_applications (id, user_id, status, store_name, description, contact, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertApplicationParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Status      string
	StoreName   string
	Description string
	Contact     string
	CreatedAt   time.Time
}

func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) error {
	_, err := q.db.Exec(ctx, insertApplication,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.StoreName,
		arg.Description,
		arg.Contact,
		arg.CreatedAt,
	)
	return err
}

const insertStore = `-- name: InsertStore :exec
INSERT INTO seller_stores (id, seller_id, name, logo_url, description, contact)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertStoreParams struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Name        string
	LogoUrl     string
	Description string
	Contact     string
}

func (q *Queries) InsertStore(ctx context.Context, arg InsertStoreParams) error {
	_, err := q.db.Exec(ctx, insertStore,
		arg.ID,
		arg.SellerID,
		arg.Name,
		arg.LogoUrl,
		arg.Description,
		arg.Contact,
	)
	return err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :exec
UPDATE seller_applications SET status = $2, reject_reason = $3, decided_at = now() WHERE id = $1
`

type UpdateApplicationStatusParams struct {
	ID           uuid.UUID
	Status       string
	RejectReason string
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) error {
	_, err := q.db.Exec(ctx, updateApplicationStatus, arg.ID, arg.Status, arg.RejectReason)
	return err
}

const updateStore = `-- name: UpdateStore :exec
UPDATE seller_stores SET name = $2, logo_url = $3, description = $4, contact = $5, updated_at = now()
WHERE seller_id = $1
`

type UpdateStoreParams struct {
	SellerID    uuid.UUID
	Name        string
	LogoUrl     string
	Description string
	Contact     string
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) error {
	_, err := q.db.Exec(ctx, updateStore,
		arg.SellerID,
		arg.Name,
		arg.LogoUrl,
		arg.Description,
		arg.Contact,
	)
	return err
}
