// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eventing.sql

package eventsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const fetchUnsentOutbox = `-- name: FetchUnsentOutbox :many
SELECT id, event_type, payload, occurred_at
FROM platform_outbox
WHERE dispatched_at IS NULL
ORDER BY created_at
LIMIT $1
`

type FetchUnsentOutboxRow struct {
	ID         uuid.UUID
	EventType  string
	Payload    []byte
	OccurredAt time.Time
}

func (q *Queries) FetchUnsentOutbox(ctx context.Context, limit int32) ([]FetchUnsentOutboxRow, error) {
	rows, err := q.db.Query(ctx, fetchUnsentOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchUnsentOutboxRow{}
	for rows.Next() {
		var i FetchUnsentOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO platform_outbox (id, event_type, payload, occurred_at)
VALUES ($1, $2, $3, $4)
`

type InsertOutboxParams struct {
	ID         uuid.UUID
	EventType  string
	Payload    []byte
	OccurredAt time.Time
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.ID,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const markOutboxDispatched = `-- name: MarkOutboxDispatched :exec
UPDATE platform_outbox
SET dispatched_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxDispatched(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxDispatched, id)
	return err
}

const markProcessed = `-- name: MarkProcessed :execrows
INSERT INTO platform_processed_events (consumer, event_id)
VALUES ($1, $2)
ON CONFLICT (consumer, event_id) DO NOTHING
`

type MarkProcessedParams struct {
	Consumer string
	EventID  uuid.UUID
}

func (q *Queries) MarkProcessed(ctx context.Context, arg MarkProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markProcessed, arg.Consumer, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
