// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformOutbox struct {
	ID           uuid.UUID
	EventType    string
	Payload      []byte
	OccurredAt   time.Time
	DispatchedAt pgtype.Timestamptz
	CreatedAt    time.Time
}

type PlatformProcessedEvent struct {
	Consumer    string
	EventID     uuid.UUID
	ProcessedAt time.Time
}
