// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	FetchUnsentOutbox(ctx context.Context, limit int32) ([]FetchUnsentOutboxRow, error)
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) error
	MarkOutboxDispatched(ctx context.Context, id uuid.UUID) error
	MarkProcessed(ctx context.Context, arg MarkProcessedParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
